fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    concat_native: 'theforeman-concat_native'
    augeasproviders_shellvar: 'herculesteam-augeasproviders_shellvar'
  symlinks:
    hostapd: "#{source_dir}"
